#!/bin/bash
echo "🚀 Complete TikTok Fitness Deployment with AI Agents"
echo "===================================================="

# Phase 1: Brand Setup with AI Agents
echo "📱 Phase 1: AI-Powered Brand Configuration"
python3 scripts/brand_generator.py
echo "✅ Brand strategy generated by AI agents"
echo "Choose your brand name and update .env"
read -p "Press enter when ready..."

# Phase 2: Launch All Subagents
echo "🤖 Phase 2: Initializing AI Subagents"
python3 scripts/engagement_agents.py &
python3 scripts/devops_agents.py &
echo "✅ All AI agents launched"

# Phase 3: DigitalOcean Deployment
echo "☁️ Phase 3: Cloud Deployment with DevOps Agents"
echo "1. DevOps Agent creating DigitalOcean Droplet..."
echo "2. Performance Agent optimizing configuration..."
echo "3. Cost Monitor Agent tracking expenses..."
read -p "Enter Droplet IP (from devops agent): " DROPLET_IP

# Phase 4: Remote Setup with Automation
ssh root@$DROPLET_IP << 'ENDSSH'
# System setup
apt-get update && apt-get upgrade -y
apt-get install -y python3-pip python3-venv ffmpeg git nginx certbot

# Project setup
cd /opt
git clone [YOUR_REPO_URL] tiktok-fitness
cd tiktok-fitness

# Python environment
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

# Install AI agents
pip install -r requirements-agents.txt

# Database
python3 scripts/init_database.py

# Service setup
cat > /etc/systemd/system/tiktok-fitness.service << EOF
[Unit]
Description=TikTok Fitness Automation with AI Agents
After=network.target

[Service]
Type=simple
User=www-data
WorkingDirectory=/opt/tiktok-fitness
Environment="PATH=/opt/tiktok-fitness/venv/bin"
ExecStart=/opt/tiktok-fitness/venv/bin/python src/core/main_controller.py start --with-agents
Restart=always

[Install]
WantedBy=multi-user.target
EOF

# Agent services
cat > /etc/systemd/system/tiktok-agents.service << EOF
[Unit]
Description=TikTok AI Agents
After=network.target

[Service]
Type=simple
User=www-data
WorkingDirectory=/opt/tiktok-fitness
Environment="PATH=/opt/tiktok-fitness/venv/bin"
ExecStart=/opt/tiktok-fitness/venv/bin/python scripts/run_all_agents.py
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable tiktok-fitness tiktok-agents
systemctl start tiktok-fitness tiktok-agents

echo "✅ Deployment complete with all AI agents!"
ENDSSH

echo "🎉 System deployed successfully with AI automation!"
echo "Monitor at: http://$DROPLET_IP:8000"
echo "AI Agents Dashboard: http://$DROPLET_IP:8000/agents"