#!/bin/bash
# YouTube Cookie Setup for Resilient Downloads

echo "============================================="
echo "YouTube Cookie Setup for Resilient Downloads"
echo "============================================="
echo ""
echo "YouTube is blocking downloads with 'Sign in to confirm you're not a bot' errors."
echo "Cookies allow us to bypass this by using an authenticated session."
echo ""
echo "Choose your setup method:"
echo ""
echo "Option 1: Automatic Extraction (Recommended)"
echo "-------------------------------------------"
echo "Run: python scripts/extract_cookies.py"
echo "This will extract cookies from Chrome/Firefox automatically"
echo ""
echo "Option 2: Browser Extension Method"
echo "----------------------------------"
echo "1. Install extension:"
echo "   Chrome: 'Get cookies.txt LOCALLY'"
echo "   Firefox: 'cookies.txt' addon"
echo ""
echo "2. Log into YouTube in your browser"
echo ""
echo "3. Click the extension icon while on youtube.com"
echo ""
echo "4. Save the file as 'config/youtube_cookies.txt'"
echo ""
echo "Option 3: Manual Developer Tools Method"
echo "---------------------------------------"
echo "1. Open YouTube and sign in"
echo "2. Press F12 to open Developer Tools"
echo "3. Go to Application > Storage > Cookies"
echo "4. Find these cookies:"
echo "   - SID, HSID, SSID, SAPISID, APISID"
echo "   - LOGIN_INFO, VISITOR_INFO1_LIVE"
echo "   - PREF, YSC, CONSENT"
echo ""
echo "5. Create config/youtube_cookies.txt with format:"
echo "   .youtube.com<TAB>TRUE<TAB>/<TAB>TRUE<TAB>0<TAB>COOKIE_NAME<TAB>COOKIE_VALUE"
echo ""
echo "Option 4: Use Invidious/Proxy (No Login Required)"
echo "-------------------------------------------------"
echo "The downloader will automatically try Invidious instances"
echo "and Cobalt API as fallbacks if cookies aren't available."
echo ""
echo "============================================="
echo "After Setup:"
echo "============================================="
echo "1. Cookies go in: config/youtube_cookies.txt"
echo "2. Set environment variable (optional):"
echo "   export YOUTUBE_COOKIE_FILE=/app/config/youtube_cookies.txt"
echo "3. The downloader will automatically use them"
echo ""
echo "Note: Cookies expire after ~30 days"
echo "Re-run setup when downloads start failing again"